[project]
name = "uv-opencv-error"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "mypackage",
    "opencv-python-headless>=4.11.0.86",
]

[tool.uv.sources]
mypackage = { path = "./mypackage/" }
